### ISSUE TITLE
How to add credentials

### ISSUE THREAD

**Issue by Spandana-Gajangi** [pkallos/winston-firehose#12]
I get error like Error: CredentialsError: Missing credentials in config

**Comment by pkallos** [comment]
Hi! The README.md links to Amazon documentation https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Firehose.html#constructor-property
Which you can pass into `firehoseOptions`:
```javascript
new WFirehose({
        'streamName': 'firehose_stream_name',
        'firehoseOptions': {
          'region': 'us-east-1',
          'credentials': <>
        }
      })
```

The documentation also provides a few other options:
- you can specify the `accessKeyId` and `secretAccessKey`
- you can specify a `credentialProvider`
