### ISSUE TITLE
Only writing to Firehose once

### ISSUE THREAD

**Issue by rohalla2** [pkallos/winston-firehose#20]
I am creating an instance of a `winston` logger with `winston-firehose` as a transport in a `logger.ts` file, then exporting that logger and using it in several areas of my application.  

The first time I log something using `logger.info()` or `logger.error()` the item is sent to Firehose as expected.  Every subsequent call does not seem to reach `winston-firehose` at all.  I placed `console.log()` statements in the `send` method of `FireHoser` and the logs are only printed for the first log.  Every log IS being logged to the Console, however, using the other transport defined at the bottom of the file.  

My logger definition is:
```typescript
import * as winston from 'winston';
const fireHose = require('winston-firehose');

export const logger: winston.Logger = winston.createLogger({
    format: winston.format.json(),
    levels: winston.config.syslog.levels,
    level: 'info',
    transports: [
        new fireHose({
            streamName: 'My stream name',
            fireHoseOptions: {
                region: 'us-east-1',
            },
        }),
    ],
});

 if (process.env.NODE_ENV !== 'production') {
     logger.add(new winston.transports.Console({
         format: winston.format.json(),
         level: 'info',
     }));
 }

```

Any advice would be appreciated.

**Comment by pkallos** [comment]
@rohalla2 thanks for reporting. Need a bit more information:
- can you let me know which version of the package you're using (from the Lockfile if possible)?
- can you include some sample code for the logging that succeeds and then subsequently fails?

**Comment by pkallos** [comment]
@rohalla2  There was an issue in  `2.02 >= v, v <= 2.0.4` after the upgrade to winston 3, but it should be fixed in the latest deployment `2.0.5`.

**Comment by rohalla2** [comment]
I upgraded from `2.0.1` to `2.0.5` and that seems to have fixed my issue.  I should have thought of that!

Thanks @pkallos

**Comment by pkallos** [comment]
great, glad it worked out and sorry for the trouble!
