### ISSUE TITLE
options.eol not implemented 

### ISSUE THREAD

**Issue by jhomarolo** [pkallos/winston-firehose#26]
Winston has an eol option (end of line) that in this plugin it does not have the option to send.

Am I missing something or is it a lack of functionality?

**Comment by pkallos** [comment]
Hi @jhomarolo , thanks for opening this issue.

> Winston has an eol option (end of line) that in this plugin it does not have the option to send.

It seems that some *specific winston transport* implementations support an `options.eol` option, but it doesn't appear to be a mandatory part of the specification. As far as I can tell only the `File`, `Console` and `Stream` library transport implementations support `options.eol` -- just skimming the documentation [here](https://github.com/winstonjs/winston/blob/master/docs/transports.md#amazon-kinesis-firehose-transport).

What is the use case for have an EOL marker in Firehose? Messages in Firehose are inherently delimited and don't need a trailing `\n`, and a common use case right now for this library is to stream into Kibana/ELK, where the messages don't benefit from trailing newlines in indexing.

You are correct this transport library currently lacks this functionality; I am very open to implementing it after understanding the use case.

My guess is if we were to implement it, we'd likely want to have the default be an empty string `''` so as not to break existing behaviors.

**Comment by jhomarolo** [comment]
My case is for using ndjson with Elastic.

Adding the line break \n , I can parse any elastic using the ndjson pattern

**Comment by pkallos** [comment]
Further detail on this, the winston Transport interface is as follows:
```typescript
  interface TransportStreamOptions {
    format?: logform.Format;
    level?: string;
    silent?: boolean;
    handleExceptions?: boolean;
    handleRejections?: boolean;

    log?(info: any, next: () => void): any;
    logv?(info: any, next: () => void): any;
    close?(): void;
  }
```

`options.eol` is part of the File transport and some other default transports.

Still, this feature could be useful so I'll work it into version 4.x, very likely the default will be `options.eol = ""` instead of `options.eol = os.EOL` as is the case with some of the baked in winston transports. Will resolve here when this is integrated. Thanks.

**Comment by pkallos** [comment]
This will go out in the next release `v4.0.0-next.1`

**Comment by ViktorCollin** [comment]
Thanks for your good work!

Is there a date planed for when the release of `v4.0.0-next.1` will happen. 
We are currently blocked on this so I'm asking to try to understand if we shall wait for the release or depend on a fork.

Keep up the good work!
